### ISSUE TITLE
header刷新高度有问题，可以由高变矮，但是不能由矮变高

### ISSUE THREAD

**Issue by dragonking-T** [weijingyunIOS/HHHorizontalPagingView#3]
需要在add headerSizeHeightConstraint时先判断是否需要移除该constraint

**Comment by haoero** [comment]
reload之前要remove self.constraints, 另外configureheader之前也要remove header.constraints否则同一个header的高度发生改变后会add多个不同的constraints，有冲突！

**Comment by CalmHeart** [comment]
为什么会向上移动70像素啊？？？
