### ISSUE TITLE
适配iOS11的问题

### ISSUE THREAD

**Issue by 18271628434** [weijingyunIOS/HHHorizontalPagingView#5]
你的demo到了ios11Tableview就会多出来一块空白。我用适配ios11的代码后，没有效果。请问怎么去适配ios11

**Comment by WydAmbition** [comment]
作者解决了这个问题了么？ 新项目准备用这个框架呀

**Comment by weijingyunIOS** [comment]
iOS11 的问题是 由于 scrollView 的  view.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever; 导致的，你可以自己加下。我近期比较忙还没处理

**Comment by weijingyunIOS** [comment]
我这两天改下

**Comment by weijingyunIOS** [comment]
年前来大活了，你先自己适配吧，唉

**Comment by weijingyunIOS** [comment]
找到原因了 ，必须实现  - (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {
    UIView *view = [UIView new];
    view.backgroundColor = [UIColor orangeColor];
    return view;
}
要不 组头高度是默认

**Comment by weijingyunIOS** [comment]
已处理，可以看 pod 1.2.1
